apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-websocket-traffic-global
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 8080
